# vim: syntax=python

Import('env')

hal = SConscript('Hal/SConscript')

kernel = env.Clone()
kernel.Append(OOCFLAGS = ['-sourcepath=Src/Kernel'],
              LINKFLAGS = ['-T', File('Linker.ld')],
              LIBS = [hal])

ooclib = kernel.Ooc('ooc.lib', 'Main.ooc')
Clean(ooclib, '#ooc_tmp')

oos = kernel.Program('oos', [
  'Boot.asm',
  'Printf.c',
  ooclib
])

Return('oos')

