# vim: syntax=python

Import('env')

hal = SConscript('Hal/SConscript')

kernel = env.Clone()
kernel.Append(OOCFLAGS = ['-sourcepath=Src/Kernel', '-entrypoint=kmain'],
              LINKFLAGS = ['-T', File('Linker.ld')],
              LIBS = [hal])

ooclib = kernel.ooc('ooc.lib', 'Main.ooc')
Clean(ooclib, '#ooc_tmp')
Clean(ooclib, '#rock_tmp')

oos = kernel.Program('oos', [
  'Boot.asm',
  ooclib
])

Depends(ooclib, Glob('*.ooc'))
Depends(ooclib, Glob('*/*.ooc'))
Depends(ooclib, Glob('#Src/OocLib/*/*.ooc'))

Return('oos')
