# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')
Import('sources', 'shiny')

sources = [
  'gdt.asm',
  'idt.c'
]

hallib = env.StaticLibrary('hal', sources)

shiny.Append(LIBS=[hallib])

distreq += [hallib]

