# vim: syntax=python

Import('env')
Import('sources', 'kernel')

sources = [
  'GDT.asm',
  'Ports.c',
  'IDT.c',
  'Interrupts.c',
  'Exceptions.asm'
]

hal = env.StaticLibrary('hal', sources)

kernel.Append(LIBS=[hal])

