# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')
Import('sources', 'shiny')

sources = [
  'GDT.asm',
  'Ports.c',
  'IDT.c',
  'Interrupts.c',
  'Exceptions.asm'
]

hallib = env.StaticLibrary('hal', sources)

shiny.Append(LIBS=[hallib])

distreq += [hallib]

