# vim: syntax=python

Import('env', 'arch', 'buildtype', 'distreq')

sources = []

shiny = env.Clone()

Export('sources', 'shiny')
SConscript('boot/%s/SConscript' % arch)
SConscript('hal/%s/SConscript' % arch)

ooc = env.Clone()
ooc.Append(OOCFLAGS=['-sourcepath=src/shiny'])

ooclib = ooc.ooc('ooc.lib', 'init/init.ooc')

sources += [
  ooclib
]

shinyexe = shiny.Program('shiny', sources)

distreq += [shinyexe]

